
# >>> Fichier de configuration du framework.
#
# ------------------------------------------------------------------------------
#
#     This file is part of the moon framework.
#
#     (c) 2013 Lambdaweb - www.lambdaweb.fr
#
#     For the full copyright and license information, please view the LICENSE
#     file that was distributed with this source code.
#

# all the database informations
database :
  
  # the database driver
  driver : "mysql"
  
  # the database hostname
  host : "localhost"
  
  # the database login
  login : "root"
  
  # the database password
  pass : "uithoorn"
  
  # the database name
  dbname : "test_lwf"
  
  # the prefix for database tables
  db_prefix : ""
 
 
system:
  # developpement mode : [DEBUG | RELEASE]
  mode:	"DEBUG" 
  
  # racine du site
  siteroot: "/moon/"
  
  # Le chemin du ou des fichiers de routage de l'utilisateur
  routes_files: ["Config/routes.yml","test/routes.yml"]
  