all: buildall

buildall:
	@echo ""
	@echo "============== BOOTSTRAP TEMPLATE ================"
	@echo "Nothing to do with this template..."
	@echo "=================================================="
	@echo ""

.PHONY: buildall